### ISSUE TITLE
Zbudowanie obudowy (dobranie obudowy)

### ISSUE THREAD

**Issue by bykowskiolaf** [BuzzVerse/lora_hardware#2]
Zamontowanie Beaglebone Black, zasilacza itd. w obudowie.

**Comment by pkamoda-shani** [comment]
Obudowa została zakupiona przez GL: https://matelsklep.pl/pl/p/Puszka-hermetyczna-300x220x120-bez-dlawika-S-BOX616/5775

Obudowa S-BOX616 z zawiasem na uszczelce.



![Image](https://github.com/BuzzVerse/lora_hardware/assets/140426706/f0d234e8-2393-463d-a96c-fcb4937f6917)
